# Generated by Django 5.1.5 on 2025-03-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='active',
        ),
    ]
